### ISSUE TITLE
Prototipo Figma... Tópicos Avanzandos de P.

### ISSUE THREAD

**Issue by marxgonzalez29** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-ingestudiantes#2]
https://www.figma.com/file/hFwwL7GndXrXG3W7NjELAc/Untitled?type=design&node-id=0%3A1&mode=dev&t=th2Htt5ka4Nbpf4m-1

Integrantes:
Emmanuel Marx Salazar González
Edgar Axel Sandoval Hernández 
[practca2_interfasGrafica.docx](https://github.com/SistemasTecTlaxiaco/actividad-1-practicaprototipo-ingestudiantes/files/14335288/practca2_interfasGrafica.docx)

**Comment by Daisy-GonzalezLita12** [comment]
Buenos días compañeros, por favor podrían subir su reporte de este trabajo, así de igual forma sus demás trabajos

**Comment by Daisy-GonzalezLita12** [comment]
Hola buenos días compañeros, su trabajo está bien, solo falto a agregar más imágenes. Porcentaje obtenido 17%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
